spring:
  application:
    name: authentication
  datasource:
    url: jdbc:mysql://localhost:3306/microService
    username: root
    password: root123456
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
server:
  port: 8080

jwt:
  secret: "cCk72!g#78r9JfGhTdP4x7q2MqLp$NkQ"
  expiration: 3600000
